title: Seve D. Kim
email: email@example.com
description: Seve Kim's website
url: "https://sevedkim.com"
twitter: sevedkim

baseurl: ""
permalink: /:categories/:title:output_ext
markdown: kramdown
plugins:
  - jekyll-feed
